database:
  host: localhost
  port: 5432
  dbname: combustiveis
  user: postgres

datasets:
  2018-01: puc-minas-proj-app-dados\ca-2018-01.csv
  2018-02: puc-minas-proj-app-dados\ca-2018-02.csv
  2020-01: puc-minas-proj-app-dados\ca-2020-01.csv
  2020-02: puc-minas-proj-app-dados\ca-2020-02.csv