database:
  host: localhost
  port: 5432
  dbname: combustiveis
  user: rafaelmacedo

datasets:
  2018-01: /Users/rafaelmacedo/Documents/Code/puc-minas-proj-app-dados/app/ca-2018-01.csv
  2018-02: /Users/rafaelmacedo/Documents/Code/puc-minas-proj-app-dados/app/ca-2018-02.csv
  2020-01: /Users/rafaelmacedo/Documents/Code/puc-minas-proj-app-dados/app/ca-2020-01.csv
  2020-02: /Users/rafaelmacedo/Documents/Code/puc-minas-proj-app-dados/app/ca-2020-02.csv